name: Release flow

on:
  push:
    tags: ['v*', '!v*\+*']

concurrency:
  group: release
  queue: max

permissions:
  contents: read

jobs:
  modules:
    uses: ./.github/workflows/_metadata.yml
    with:
      commit-sha: ${{ github.sha }}

  release:
    needs: modules
    uses: ./.github/workflows/_publish.yml
    with:
      commit-sha: ${{ github.sha }}
      release-tag: ${{ github.ref_name }}
      modules-tag: ${{ needs.modules.outputs.modules-tag }}
      evaluation-matrix: ${{ needs.modules.outputs.matrix }}
    secrets:
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

  notify:
    needs: [modules, release]
    uses: ./.github/workflows/_notify.yml
    with:
      modules-tag: ${{ needs.modules.outputs.modules-tag }}
      clients: '[{"tag": "${{ github.ref_name }}"}]'
    secrets:
      RELEASE_APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
